version: "3.8"

services:
  backend:
    container_name: nest-backend
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
    volumes:
      - ./backend:/app

  postgres:
    container_name: nest-postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: moviebooker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - moviebookerDB:/var/lib/postgresql/data

volumes:
  moviebookerDB:
