version: "3.8"

services:
  backend:
    container_name: nest-backend
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=super-secret-key
      - DB_HOST=locaolhost
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=moviebooker
    depends_on:
      - postgres
    volumes:
      - ./backend:/app

  postgres:
    container_name: nest-postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: moviebooker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - moviebookerDB:/var/lib/postgresql/data

volumes:
  moviebookerDB:
