version: "3.8"

services:
  backend:
    container_name: moviebooker-backend
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env.local
      - ./backend/.env
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
    volumes:
      - ./backend:/app

  frontend:
    container_name: moviebooker-frontend
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.local
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

  postgres:
    container_name: moviebooker-postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: moviebooker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - moviebookerDB:/var/lib/postgresql/data

volumes:
  moviebookerDB:
